### PR TITLE
Support posting JSON.

### PR DESCRIPTION
**Pull request by gabrielf**

### CODE REVIEW

**Comment by gabrielf** [comment]
Or maybe the API should be changed so that arbitrary data can be posted with a content type set by the caller to avoid an explosion of PostX methods?

**Comment by mrjones** [comment]
Thanks for the patch!

Yup. You're totally right that the API is wrong.

I've been thinking about exposing something that implements http.Client (or hopefully, a http.RoundTripper, which is a narrower interface that is easy to turn into a http.Client).  I think that would give (almost?) everyone the flexibility they need without adding a new method for every use case.

I'm going to merge this for now though, until I get around to doing something properly.  (Thanks for the test, it will make it easier to make sure any new ideas work properly).

**Comment by jgautheron** [comment]
:+1:

**Comment by mrjones** [comment]
FYI I took your suggestion of changing the API and exposed a full http.Client (available via MakeHttpClient.

I think it would work really well for this use case.  If you've got the time and interest take a look and let me know how it works for you.

(FYI here's the commit 5faa557585ac2fde321eada0a28eb6f1b4176319)

**Comment by gabrielf** [comment]
Nice! I agree that it is hard to expose a full HTTP interface in almost any other way. I've tested the new version in a Google App Engine app where a custom HTTP Client is used (appengine/urlfetch) and it works fine.

**Pull request merged**
