### PR TITLE
Pass through context to enable request timeouts

### PR DESCRIPTION
**Pull request by johnboiles**

### CODE REVIEW

**Comment by mrjones** [comment]
Hi, thanks for the patch!

Unfortunately, this changes the signature of a number of existing methods which would break calling code in other repos.  Admittedly, these functions are deprecated ... however, the reason they're deprecated and not just entirely deleted is that I wanted to avoid breaking third-party callers.

I'm not sure if this would work, but here's an idea:
All these methods (Get/Post/Put/Delete/...) have been replaced by MakeHttpClient which returns an http.Client (https://golang.org/pkg/net/http/#Client).  http.Client.Do takes a http.Request as input, and http.Request has the withContext which seems like the key to achieving your goal.  Would it be possible for you to refactor your code to use MakeHttpClient rather than Get/Post/Put/... directly?

If that doesn't work, please do let me know so we can figure out a way to make this go.

Thanks!

- Matt

**Comment by johnboiles** [comment]
Thanks for the feedback! I'll give that a shot.

What do you think about marking these methods as deprecated in the Golang format as documented [here](https://blog.golang.org/godoc-documenting-go-code)? e.g. instead of 
```
// ** DEPRECATED **
// Please call Get on the http client returned by MakeHttpClient instead!
```
you'd have
```
// Deprecated: Please call Get on the http client returned by MakeHttpClient instead!
```

In JetBrains' Goland (and maybe other IDEs), using the standard Golang format for this causes any uses of the method to show with strikethrough text, making it more obvious that the method is deprecated. I didn't even notice the comment that these methods were deprecated!
image

**Comment by johnboiles** [comment]
Refactoring my code to use `MakeHttpClient` worked just fine! That seems like a much better way to structure things for your library.

LMK if you want me to make the changes to the `DEPRECATED` comments. Happy to submit a PR.

**Comment by mrjones** [comment]
Great to hear everything worked!

Thanks for letting me know about the "deprecated" comment format.  If you want to submit a PR to change them, I'd be happy to merge it!

**Pull request closed without merging**
